### PR TITLE
Updater Hardening

### PR DESCRIPTION
**Pull request by xander-io**
All,

Just made some minor "hardening" improvements to the update logic.
My full write-up behind this can be found on [Diaspora](https://3.basecamp.com/3671212/buckets/7351439/messages/5270890395).

I am by no means a TCL expert. So please feel free to provide feedback if there is something incorrect or needs to be modified!

### CODE REVIEW

**Comment by decentjohn** [comment]
Continued conversation here:
https://3.basecamp.com/3671212/buckets/7351439/messages/5270890395

**Comment by xander-io** [comment]
Hey @decentjohn - replied. Only change that needs to happen to mimic previous behavior is line 566 to `if {has_tls != 1}{}`. All the rest of my changes aren’t necessary. Once changed, I’ll close the pull request.

**Comment by decentjohn** [comment]
you're right, thanks for noticing the logic error.
https://github.com/decentespresso/de1app/commit/f2305598e7403476b4a1503f2c3ce6bf6c510bcc

**Comment by xander-io** [comment]
Awesome! Closing this.

**Pull request closed without merging**
