### PR TITLE
logging: Log background errors; run-time, skin-load, and plugin-load

### PR DESCRIPTION
**Pull request by jeffsf**
Timestamps or details of background errors were not
captured in the logs with the default bgerror handler.
Log the details of the error then defer to the
standard bgerror handler.

Users will see the modal popup that Tk provides
currently. The can continue to use it as before
keeping the current behavior, including "skip".

Signed-Off-By: Jeff Kletsky <git-commits@allycomm.com>

### CODE REVIEW

**Comment by jeffsf** [comment]
Logs with or without user input, with a timestamp at the time the error was pulled from the list. 
(The first one is generally very close, the others will be delayed due to interaction with the Tk error handler)

_**This is usable now. Draft only as I'd like to add the underlying function to load of skins and plugins as well.**_

As an example:
```
2021-03-28 18:10:52.278 NOTICE: tare request declined as after 169 ms (1616980252.109)
2021-03-28 18:10:52.423 ERROR: invalid command name "cause_an_error"
-errorcode TCL LOOKUP COMMAND cause_an_error
-code 1
-level 0
-errorstack INNER {invokeStk1 cause_an_error} CALL {::skin::dsx::append_live_data_to_espresso_chart_orig {event_time 1616980252.414 update_received 1616980252.412 SteamTemp 158 SetGroupPressure 0.0 MixTemp 91.75390625 GroupFlow 0.587646484375 HeadTemp 90.26339721679688 SetMixTemp 19.578125 SampleTime 34257 HeadTemp1 90 SetGroupFlow 1.0 HeadTemp2 67 HeadTemp3 110 SetHeadTemp 90.0 FrameNumber 3 GroupPressure 0.00341796875 this_state Espresso this_substate {final heating}}} CALL {::gui::update::append_live_data_to_espresso_chart {event_time 1616980252.414 update_received 1616980252.412 SteamTemp 158 SetGroupPressure 0.0 MixTemp 91.75390625 GroupFlow 0.587646484375 HeadTemp 90.26339721679688 SetMixTemp 19.578125 SampleTime 34257 HeadTemp1 90 SetGroupFlow 1.0 HeadTemp2 67 HeadTemp3 110 SetHeadTemp 90.0 FrameNumber 3 GroupPressure 0.00341796875 this_state Espresso this_substate {final heating}}} CALL {::gui::callbacks::on_shotvalue_available {event_time 1616980252.414 update_received 1616980252.412 SteamTemp 158 SetGroupPressure 0.0 MixTemp 91.75390625 GroupFlow 0.587646484375 HeadTemp 90.26339721679688 SetMixTemp 19.578125 SampleTime 34257 HeadTemp1 90 SetGroupFlow 1.0 HeadTemp2 67 HeadTemp3 110 SetHeadTemp 90.0 FrameNumber 3 GroupPressure 0.00341796875 this_state Espresso this_substate {final heating}}} CALL ui_startup
-errorinfo invalid command name "cause_an_error"
    while executing
"cause_an_error"
    (procedure "::skin::dsx::append_live_data_to_espresso_chart_orig" line 3)
    invoked from within
"::skin::dsx::append_live_data_to_espresso_chart_orig $event_dict {*}$args"
    (procedure "::gui::update::append_live_data_to_espresso_chart" line 7)
    invoked from within
"::gui::update::append_live_data_to_espresso_chart $event_dict"
    (procedure "::gui::callbacks::on_shotvalue_available" line 6)
    invoked from within
"::gui::callbacks::on_shotvalue_available {event_time 1616980252.414 update_received 1616980252.412 SteamTemp 158 SetGroupPressure 0.0 MixTemp 91.75390..."
    ("after" script)
-errorline 1
2021-03-28 18:10:52.486 DEBUG: ::device::scale::history::on_tare_seen
```

**Comment by jeffsf** [comment]
Version bump on logging.tcl as about to use it elsewhere

**Comment by jeffsf** [comment]
Well, that was strange, lost a comment somehow.

Since I'm typing "opts_dict" for "options dictionary" go with that (ref: https://www.tcl-lang.org/man/tcl/TclCmd/catch.htm)

Here's some example log output
```
2021-03-28 18:10:52.278 NOTICE: tare request declined as after 169 ms (1616980252.109)
2021-03-28 18:10:52.423 ERROR: invalid command name "cause_an_error"
-errorcode TCL LOOKUP COMMAND cause_an_error
-code 1
-level 0
-errorstack INNER {invokeStk1 cause_an_error} CALL {::skin::dsx::append_live_data_to_espresso_chart_orig {event_time 1616980252.414 update_received 1616980252.412 SteamTemp 158 SetGroupPressure 0.0 MixTemp 91.75390625 GroupFlow 0.587646484375 HeadTemp 90.26339721679688 SetMixTemp 19.578125 SampleTime 34257 HeadTemp1 90 SetGroupFlow 1.0 HeadTemp2 67 HeadTemp3 110 SetHeadTemp 90.0 FrameNumber 3 GroupPressure 0.00341796875 this_state Espresso this_substate {final heating}}} CALL {::gui::update::append_live_data_to_espresso_chart {event_time 1616980252.414 update_received 1616980252.412 SteamTemp 158 SetGroupPressure 0.0 MixTemp 91.75390625 GroupFlow 0.587646484375 HeadTemp 90.26339721679688 SetMixTemp 19.578125 SampleTime 34257 HeadTemp1 90 SetGroupFlow 1.0 HeadTemp2 67 HeadTemp3 110 SetHeadTemp 90.0 FrameNumber 3 GroupPressure 0.00341796875 this_state Espresso this_substate {final heating}}} CALL {::gui::callbacks::on_shotvalue_available {event_time 1616980252.414 update_received 1616980252.412 SteamTemp 158 SetGroupPressure 0.0 MixTemp 91.75390625 GroupFlow 0.587646484375 HeadTemp 90.26339721679688 SetMixTemp 19.578125 SampleTime 34257 HeadTemp1 90 SetGroupFlow 1.0 HeadTemp2 67 HeadTemp3 110 SetHeadTemp 90.0 FrameNumber 3 GroupPressure 0.00341796875 this_state Espresso this_substate {final heating}}} CALL ui_startup
-errorinfo invalid command name "cause_an_error"
    while executing
"cause_an_error"
    (procedure "::skin::dsx::append_live_data_to_espresso_chart_orig" line 3)
    invoked from within
"::skin::dsx::append_live_data_to_espresso_chart_orig $event_dict {*}$args"
    (procedure "::gui::update::append_live_data_to_espresso_chart" line 7)
    invoked from within
"::gui::update::append_live_data_to_espresso_chart $event_dict"
    (procedure "::gui::callbacks::on_shotvalue_available" line 6)
    invoked from within
"::gui::callbacks::on_shotvalue_available {event_time 1616980252.414 update_received 1616980252.412 SteamTemp 158 SetGroupPressure 0.0 MixTemp 91.75390..."
    ("after" script)
-errorline 1
2021-03-28 18:10:52.486 DEBUG: ::device::scale::history::on_tare_seen
```

**Comment by jeffsf** [comment]
More fun stuff on the way:
```
2021-03-28 19:01:02.814 INFO: set_de1_screen_saver_directory
2021-03-28 19:01:02.818 ERROR: invalid command name "crash_from_sourced_file"
-errorcode TCL LOOKUP COMMAND crash_from_sourced_file
-code 1
-level 0
-errorstack INNER {invokeStk1 crash_from_sourced_file} CALL load_skin CALL load_skin CALL load_skin CALL load_skin
-errorinfo invalid command name "crash_from_sourced_file"
    while executing
"crash_from_sourced_file"
    (file "/Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app-devel/de1plus/skins/default/de1_skin_settings.tcl" line 7)
    invoked from within
"source "[homedir]/skins/default/de1_skin_settings.tcl""
    (file "/Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app-devel/de1plus/skins/default/standard_includes.tcl" line 55)
    invoked from within
"source "[homedir]/skins/default/standard_includes.tcl""
    (file "/Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app-devel/de1plus/skins/Insight/skin.tcl" line 7)
    invoked from within
"source "[skin_directory]/skin.tcl""
-errorline 11
2021-03-28 19:01:02.819 INFO: message_page failed because: 'can't read "::message_label": no such variable'
2021-03-28 19:01:02.819 INFO: Failed to 'load_skin' because: 'invalid command name "crash_from_sourced_file"'
2021-03-28 19:01:02.820 INFO: ::plugins preloading DGUI
```

**Comment by jeffsf** [comment]
From "real life" testing, at least on macOS
```
2021-03-28 19:20:07.002 INFO: ::plugins sourcing web_api
2021-03-28 19:20:07.048 ERROR: can't find package wibble
-code 1
-level 0
-errorstack INNER {invokeStk1 package require wibble} CALL {::plugins::read web_api} CALL {::plugins::read web_api} CALL {preload web_api}
-errorcode TCL PACKAGE UNFOUND
-errorinfo can't find package wibble
    while executing
"package require wibble"
    (file "/Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app/de1plus/plugins/web_api/plugin.tcl" line 1)
    invoked from within
"::source "[homedir]/[plugin_directory]/${plugin}/plugin.tcl""
    (procedure "::plugins::read" line 7)
    invoked from within
"::plugins::read $plugin"
-errorline 24
2021-03-28 19:20:07.049 INFO: page_display_change ->infopage
2021-03-28 19:20:07.049 INFO: Loading skin image from disk: /Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app/de1plus/skins/default/1280x800/settings_message.png
2021-03-28 19:20:07.049 INFO: page_display_change image create photo infopage -file /Volumes/miniup-users/jeff/Documents/DecentEspresso/de1app/de1plus/skins/default/1280x800/settings_message.png
2021-03-28 19:20:07.151 INFO: Switched to page: infopage
```

**Comment by jeffsf** [comment]
Correct typo in a `msg` string
Make sure `plugins.tcl` gets at least `de1_logging 1.1`

**Review by Mimoja — APPROVED** [review]

**Pull request merged**
