### PR TITLE
Multiple profiles

### PR DESCRIPTION
**Pull request by barneyhawes**
Extracted the code for populating a listbox with profile titles and for setting the current profile into separate functions in order to support skins with multiple profiles.
See: [https://3.basecamp.com/3671212/buckets/7351439/messages/3208787084#__recording_3209888313](https://3.basecamp.com/3671212/buckets/7351439/messages/3208787084#__recording_3209888313)

### CODE REVIEW

**Comment by barneyhawes** [comment]
I'm not sure why there is a file conflict here. The individual commits are each quite straightforward. I cannot see how to view the conflict (the Resolve conflicts button is disabled because I do not have write access) so I can't see how to investigate the conflict further.

**Comment by barneyhawes** [comment]
I have made use of these changes to implement a custom UI for switching profiles in the [Metric skin](https://github.com/barneyhawes/decent-metric), so feel free to use this for testing these changes.

**Comment by decentjohn** [comment]
'resolve conflicts' is also hidden for me.

Let's see what @Mimoja has to say about this when she wakes up.  She's getting over a cold, so it might be more than a day...

**Comment by barneyhawes** [comment]
OK John, no problem.
You should be able to see the proposed changes by clicking "Commits" above this chat.

**Comment by barneyhawes** [comment]
Update: I have updated my fork and this branch, so this Pull Request is now conflict free.
FYI, the conflict was caused by the the main directory name changing from "de1beta" to "de1plus".

**Comment by decentjohn** [comment]
oh great!

FYI I'm just waiting for Johanna to get well, so she and I can go through this together.  It's not clear to me what the process is for reviewing code submissions and actually running them.  I don't really want to approve code changes without running them.

Is that going to mess you up, if we wait a few more days?

**Comment by barneyhawes** [comment]
Let's wait and do it right. Get well soon Johanna!

**Pull request merged**
