### PR TITLE
Catch and log errors in early loading and execution

### PR DESCRIPTION
**Pull request by jeffsf**
Errors prior to when the GUI is up and running are presently "invisible", with often only the failure of the GUI to start the only evidence.

This builds on the logging system introduced in #56 by adding `try`/`on error` around the loading of `de1_main` and running of `de1_ui_startup` (https://github.com/decentespresso/de1app/pull/61/commits/5798fa8648a3ed46071507828da0d98564a09654 repeated here from that PR)

Though the output is "ugly" (raw dump of the options dict), it should be helpful to programmers in diagnosing issues in their code.

### CODE REVIEW

**Comment by jeffsf** [comment]
Example output:


2021-02-16 21:49:46.016 CRITICAL: Untrapped error loading de1_main with result: missing close-brace: possible unbalanced brace in comment
2021-02-16 21:49:46.076 CRITICAL: -code 1 -level 0 -errorcode NONE -errorinfo missing\ close-brace:\ possible\ unbalanced\ brace\ in\ comment\n\ \ \ \ while\ executing\n\"namespace\ eval\ ::de1::sav\ \{\"\n\ \ \ \ (file\ \"./binary.tcl\"\ line\ 1586)\n\ \ \ \ invoked\ from\ within\n\"source\ ./binary.tcl\"\n\ \ \ \ (\"package\ ifneeded\ de1_binary\ 1.1\"\ script)\n\ \ \ \ invoked\ from\ within\n\"package\ require\ de1_binary\"\n\ \ \ \ (file\ \"./main.tcl\"\ line\ 21)\n\ \ \ \ invoked\ from\ within\n\"source\ ./main.tcl\"\n\ \ \ \ (\"package\ ifneeded\ de1_main\ 1.0\"\ script)\n\ \ \ \ invoked\ from\ within\n\"package\ require\ de1_main\"\n\ \ \ \ (\"try\"\ body\ line\ 2) -errorline 2 -errorstack {INNER {syntax {missing close-brace: possible unbalanced brace in comment} {-code 1 -level 0 -errorcode NONE -errorinfo missing\ close-brace:\ possible\ unbalanced\ brace\ in\ comment\n\ \ \ \ while\ executing\n\"namespace\ eval\ ::de1::sav\ \{\" -errorline 1586}}}
2021-02-16 21:49:46.077 CRITICAL: Exiting

**Comment by ebengoechea** [comment]
Is this showing the actual errors where we only used to get some generic message? If that's the case, I will be really grateful, Jeff. I've lost so MANY hours tracking down silly syntax errors.

**Comment by jeffsf** [comment]
@ebengoechea 

There are two things going on, from what I can figure. 

The first is that error localization when it comes ti syntax is not very good in Tcl, in general. That I can't do much about. 

This PR addresses the cases when there is typically no useful way to get the error messages to the user. While they would typically be displayed on the console, there typically isn't one easily available when running on the tablet. Once the GUI is up and running, this kind of exception information is generally shown in the skip/save error-message popup. 

The example above comes from a situation where the behavior on the tablet is that you click on the DE1 icon, "nothing happens", then you see the Android launcher again. Although many of these errors can be "seen" running your local code with `path/to/wish de1app.tcl` from a console, most of what I have been working on requires a real scale and real DE1 connected over Bluetooth to monitor and improve real-time behavior. For most "skin" work, running from a console would give you comparable results, something like this:

```
de1app-devel/de1plus]$ /usr/local/bin/wish de1app.tcl 
Error in startup script: missing close-brace: possible unbalanced brace in comment
    while executing
"namespace eval ::de1::sav {"
    (file "./binary.tcl" line 1586)
    invoked from within
"source ./binary.tcl"
    ("package ifneeded de1_binary 1.1" script)
    invoked from within
"package require de1_binary"
    (file "./main.tcl" line 21)
    invoked from within
"source ./main.tcl"
    ("package ifneeded de1_main 1.0" script)
    invoked from within
"package require de1_main"
    (file "de1app.tcl" line 12)
```

**Comment by ebengoechea** [comment]
Thanks for all the details @jeffsf, understood.

**Comment by Mimoja** [comment]
merged

**Pull request closed without merging**
