### PR TITLE
Implement event system, improve scale handing, SAW, SAV, and GUI separation

### PR DESCRIPTION
**Pull request by jeffsf**
This PR builds on

#56 Improving Mass and Mass-Flow Estimates
#59 Correct errors in volume estimation and line frequency

with the continued objectives of:

* Getting the DE1 app to collect and record robust, time-aligned data usable by a variety of GUI implementations and post-analysis

* Providing clean integration points for extensions and GUIs ("skins") so that extension and skin authors do not have to duplicate long runs of code to be able to make additions or modifications and later manually find and merge any upstream changes into their work.

* Improving maintainability and readability of the app by
  - Modularizing long runs of straight-line code
  - Organizing code by function
  - Reducing the use of globals
  - Separating GUI function from core function

* Correcting logical and computational errors in the existing app

while preserving the functionality of the core app and its popular "skins".

In cases where the logic was primarily GUI related, it was preserved. A specific example of this is `append_live_data_to_espresso_chart`.

This work has been tested on a DE1+ v1.3 running firmware 1238, a Skale II, on the stock, K811C tablet.
As the low-level functionality of the Bluetooth stack has not been altered, these should be tablet-independent changes.

This represents my "daily driver" and will be rebased periodically as needed to adopt upstream changes.

```
$ git log -1 $(git merge-base main HEAD)
commit 2ab1d98 (upstream/main, upstream/HEAD, mini/main, main)
Author: Mimoja <git@mimoja.de>
Date:   Wed Feb 24 11:17:57 2021 +0100

    example_plugin: use local settings variable to clean up logic
    
    Signed-off-by: Mimoja <git@mimoja.de>
```

### CODE REVIEW

**Comment by jeffsf** [comment]
Corrected minor error in commit message

**Comment by jeffsf** [comment]
DO NOT MERGE

Testing underway after significant rebase onto 5d92521 (upstream/main, upstream/HEAD, main) Fix beverage tpye in the new profiles

Contents of #64 and #65 removed from this branch for stand-alone evaluation and potential merge.

Still need to check compatibility with Mimoja Cafe and get a DSx-enabling plugin/patch available

**Comment by jeffsf** [comment]
Added documentation around what the lifecycle of a shot looks like from the perspective of the "core" and what the some of the integration points are to the GUI.

**Comment by jeffsf** [comment]
Adjust autotare to accomodate 0.01 g scales -- in response to continuing and unexpected tare with 0.01 g scale on Stable

Expanded event_dict of some events based on exploratory work around writing extensions against them, as well as future time-base reconstruction.

Checking DSx changes with Damian; external to this PR.

Will not show high-res scale data at this tie as the doubling behavior of the Skale's reports can be confusing and adds little information without getting them back on a more accurate time base. (Delay and estimation improvements are "free" for most skins, and are still included)

Updated docs

**Comment by jeffsf** [comment]
Holding as draft until I can get confirmation on the DSx changes

**Comment by jeffsf** [comment]
Rebased on current main
```
$ git log -1 $(git merge-base pr-shotsample-sav-2021-02  upstream/main)
commit c3b7af6 (upstream/main, upstream/HEAD)
Author: Mimoja <git@mimoja.de>
Date:   Tue Mar 16 18:29:54 2021 +0100

    Clip advanced flow and pressure values to positive values
    
    Signed-off-by: Mimoja <git@mimoja.de>
```

DSx changes confirmed to work on Beta, as well as on Stable (backwards compatible). Pingged D to make sure I'm retaining his intent, as well as not perpetuating any non-intended changes to core behavior.

"Standard" skins (those that have not, for example, overridden or hooked `::append_live_data_to_espresso_chart` should require no changes. Spot checked on Insight and MimojaCafe.

**Comment by decentjohn** [comment]
@jeffsf seems like you think this is ready to merge, is that right?

github is showing me:
This pull request is still a work in progress
Draft pull requests cannot be merged.

and i'm unclear what I need to do to merge.  It seems that there's a conflict on bluetooth.tcl:
https://github.com/decentespresso/de1app/pull/79

This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
de1plus/bluetooth.tcl

**Comment by jeffsf** [comment]
I've been waiting for D to comment on DSx changes, but I know he's been working on other things. The changes are to two files in DSx_Code_Files and we can supply them to help ensure success for DSx users. DSx still works to make espresso without the updates, just doesn't implement some of the DSx add-ons to behavior (and won't take advantage of the delay to get final drink weight "right")

Commit 5b3216b and perhaps commit 12ae45e will force me to rebase and resolve the conflicts.

i'll ping you on this and a couple other things when I get the rebase worked out and retested (retested is the hidden cost)

**Comment by jeffsf** [comment]
Changes to proc naming in other commits incorporated (they don't show up as conflicts as they're in different places)

Basic tests passed on Insight and DSx

Ping in to @decentjohn on DD

**Comment by jeffsf** [comment]
Corrected typos in commit massage b5b4ed4

Removed redundant tare as discussed last evening/morning

Preemptively allowed for 0.000 ± 0.04 g to be considered as "close enough to zero" -- may need to revisit with, perhaps, median filtering, for high-resolution scales in high-vibration environments. Will need "real world" data (which the app collects as of commit b619ebf) to evaluate how best to handle, if it is a problem at all.

Updated docs to reflect changes.

Did not change rebase point as still fresh and orthogonal to subsequent changes

```
$ git log -1 $(git merge-base pr-shotsample-sav-2021-02 upstream/main)
commit cee9a33
Author: Mimoja <git@mimoja.de>
Date:   Fri Mar 19 15:05:10 2021 +0100

    fixup! Only touch flow and pressure if they actually exist

$ git log --pretty=oneline cee9a33..upstream/main 
7c3c357 (tag: v1.34.25, upstream/main, upstream/HEAD, mini/main, main) v1.34.25
711df14 Update Metric skin to 2.2

```

**Pull request merged**
