### PR TITLE
Increase tapping area of dcombobox dropdown. DUI pages adapt to theme

### PR DESCRIPTION
**Pull request by ebengoechea**
This brings 2 main updates to DUI:

1. The "clickable" area of the dropdown arrow of dcomboboxes was too small and often several touches were needed. It has been modified to be a dbutton with a bigger clickable area. This change needs matching updates in both DYE & MimojaCafe.

2. DUI auxiliar pages "dui_number_editor" and "dui_item_selector" now can be rethemed on the fly by passing a named argument -theme to the "dui page load" command. This is used to adapt its aspect to the page that opens them.

Other minor changes:

- dui::page::theme gets a new argument 'default'.
- dui::page::retheme now validates new_theme and logs invalid themes.
- Styles of buttons in dui_number_editor are now moved to the global theme.
- dui::item::relocate_text_wrt now can work with items different that text

### CODE REVIEW

**Comment by ebengoechea** [comment]
This PR now includes 2 new commits:

1. f195c65 finally moves everything in 'add_de1_page' to dui::page::add, making 'add_de1_page' deprecated. Also includes a lot of commented code cleanup in preparation for the next beta/stable.

2. dui::item::enable, dui::item::disable and dui::item::enable_or_disable now take options -current and -initial in the same way as dui::item::show, dui::item::hide and dui::item::show_or_hide. Bug detected by @Damian-AU

**Comment by ebengoechea** [comment]
Added a new commit 82f36a that improves the documentation by adding an "API Index" section with links to all the DUI commands.

**Comment by ebengoechea** [comment]
Added a new commit 85eac8a that adds a new value "round_outline" of the -shape option for dbuttons. It draws rounded rectangle buttons that have both a fill color and an outline. [Requested](https://3.basecamp.com/3671212/buckets/7351439/messages/3803211859#__recording_3904096091) by @decentjohn.

**Comment by Mimoja** [comment]
Updated together with DYE, MimojaCafe and metric

**Pull request merged**
