### PR TITLE
SWDark4: Remove unused append_live_data_to_espresso_chart_*

### PR DESCRIPTION
**Pull request by jeffsf**
SWDark contains two copies of append_live_data_to_espresso_chart
that appear to have been taken from two, different, past versions.

They are presently unused and believed obsolete.

They cause "false positives" during refactoring and test as they
contain references that are the same as the core version.

Removing to improve maintainability and understandability.

Future changes should consider use of the event system once merged.

Signed-Off-By: Jeff Kletsky <git-commits@allycomm.com>

### CODE REVIEW

**Comment by jeffsf** [comment]
de1app/de1plus]$ git log --pretty=oneline -1
dbf784f (HEAD -> main, upstream/main, upstream/HEAD, mini/main) re-added profile-var beverage_type as per https://3.basecamp.com/3671212/buckets/7351439/todos/3464853833#__recording_3466343787

de1app/de1plus]$ fgrep -r append_live_data_to_espresso_chart skins/*
skins/SWDark4/swdark_functions.tcl:proc append_live_data_to_espresso_chart_sw {} {
skins/SWDark4/swdark_functions.tcl:		#puts "append_live_data_to_espresso_chart $::de1(pressure)"
skins/SWDark4/swdark_functions.tcl:proc append_live_data_to_espresso_chart_restesting {} {
skins/SWDark4/swdark_functions.tcl:		#puts "append_live_data_to_espresso_chart $::de1(pressure)"

**Comment by Mimoja** [comment]
Looks fine to me, testing outstanding :)

**Comment by jeffsf** [comment]
Pingged Spence for confirmation on DD

**Comment by xpenno255** [comment]
Signed off spencerwebb189@gmail.com.  Thanks for cleaning up after me

**Comment by jeffsf** [comment]
Commit message change only to reflect Spencer's review

**Pull request merged**
